import type { MetricDefinition } from "./types";

export const METRIC_CATALOG: MetricDefinition[] = [
  {
    id: "total_revenue",
    name: "Total Revenue",
    category: "Revenue",
    formula: "SUM(net_revenue)",
    description:
      "Total net revenue after discounts and returns across all regions and products.",
    unit: "USD",
    cube: "OrdersCube",
    dimensions: ["region", "product_category", "customer_tier", "date"],
    compatibleCharts: ["line", "bar", "table"],
    summaryOperation: "sum",
    favorableDirection: "up",
  },
  {
    id: "gross_margin",
    name: "Gross Margin",
    category: "Profitability",
    formula:
      "(SUM(net_revenue) - SUM(cost_of_goods_sold)) / SUM(net_revenue) * 100",
    description:
      "Gross profit margin percentage, calculated as (Revenue - COGS) / Revenue.",
    unit: "%",
    cube: "OrdersCube",
    dimensions: ["region", "product_category", "date"],
    compatibleCharts: ["line", "bar"],
    summaryOperation: "average",
    favorableDirection: "up",
  },
  {
    id: "net_profit",
    name: "Net Profit",
    category: "Profitability",
    formula:
      "SUM(net_revenue) - SUM(cost_of_goods_sold) - SUM(operating_expenses)",
    description: "Net profit after deducting COGS and operating expenses.",
    unit: "USD",
    cube: "OrdersCube",
    dimensions: ["region", "product_category", "date"],
    compatibleCharts: ["line", "bar", "table"],
    summaryOperation: "sum",
    favorableDirection: "up",
  },
  {
    id: "churn_rate",
    name: "Customer Churn Rate",
    category: "Customer",
    formula:
      "(Customers at Start - Customers at End) / Customers at Start * 100",
    description: "Percentage of customers lost during the period.",
    unit: "%",
    cube: "CustomersCube",
    dimensions: ["region", "customer_tier", "date"],
    compatibleCharts: ["line", "bar"],
    summaryOperation: "average",
    favorableDirection: "down",
  },
  {
    id: "nrr",
    name: "Net Revenue Retention",
    category: "Growth",
    formula:
      "(Starting MRR + Expansion - Contraction - Churn) / Starting MRR * 100",
    description:
      "Net revenue retained from existing customers, including expansion and churn.",
    unit: "%",
    cube: "CustomersCube",
    dimensions: ["region", "customer_tier", "date"],
    compatibleCharts: ["line", "bar"],
    summaryOperation: "average",
    favorableDirection: "up",
  },
  {
    id: "arpu",
    name: "Average Revenue Per User",
    category: "Revenue",
    formula: "SUM(net_revenue) / COUNT(DISTINCT customer_id)",
    description: "Average revenue generated per unique customer in the period.",
    unit: "USD",
    cube: "OrdersCube",
    dimensions: ["region", "customer_tier", "product_category", "date"],
    compatibleCharts: ["line", "bar"],
    summaryOperation: "average",
    favorableDirection: "up",
  },
  {
    id: "total_orders",
    name: "Total Orders",
    category: "Efficiency",
    formula: "COUNT(DISTINCT order_id)",
    description: "Total number of unique orders placed in the period.",
    unit: "#",
    cube: "OrdersCube",
    dimensions: ["region", "product_category", "customer_tier", "date"],
    compatibleCharts: ["line", "bar", "table"],
    summaryOperation: "sum",
    favorableDirection: "up",
  },
  {
    id: "avg_order_value",
    name: "Average Order Value",
    category: "Efficiency",
    formula: "SUM(net_revenue) / COUNT(DISTINCT order_id)",
    description: "Average revenue per order.",
    unit: "USD",
    cube: "OrdersCube",
    dimensions: ["region", "product_category", "customer_tier", "date"],
    compatibleCharts: ["line", "bar"],
    summaryOperation: "average",
    favorableDirection: "up",
  },
  {
    id: "customer_count",
    name: "Active Customers",
    category: "Customer",
    formula: "COUNT(DISTINCT customer_id)",
    description:
      "Number of unique customers with at least one order in the period.",
    unit: "#",
    cube: "CustomersCube",
    dimensions: ["region", "customer_tier", "date"],
    compatibleCharts: ["line", "bar", "table"],
    summaryOperation: "latest",
    favorableDirection: "up",
  },
  {
    id: "new_customers",
    name: "New Customers",
    category: "Growth",
    formula:
      "COUNT(DISTINCT CASE WHEN first_order_date IN period THEN customer_id END)",
    description: "Number of customers who placed their first order in the period.",
    unit: "#",
    cube: "CustomersCube",
    dimensions: ["region", "customer_tier", "date"],
    compatibleCharts: ["bar", "line"],
    summaryOperation: "sum",
    favorableDirection: "up",
  },
  {
    id: "revenue_by_region",
    name: "Revenue by Region",
    category: "Revenue",
    formula: "SUM(net_revenue) GROUP BY region",
    description: "Total revenue broken down by geographic region.",
    unit: "USD",
    cube: "OrdersCube",
    dimensions: ["region", "date"],
    compatibleCharts: ["bar", "pie", "table"],
    summaryOperation: "sum",
    favorableDirection: "up",
  },
  {
    id: "revenue_by_category",
    name: "Revenue by Product Category",
    category: "Revenue",
    formula: "SUM(net_revenue) GROUP BY product_category",
    description: "Total revenue broken down by product category.",
    unit: "USD",
    cube: "OrdersCube",
    dimensions: ["product_category", "date"],
    compatibleCharts: ["bar", "pie", "table"],
    summaryOperation: "sum",
    favorableDirection: "up",
  },
  {
    id: "cogs",
    name: "Cost of Goods Sold",
    category: "Profitability",
    formula: "SUM(cost_of_goods_sold)",
    description:
      "Total direct costs attributable to the production of goods sold.",
    unit: "USD",
    cube: "OrdersCube",
    dimensions: ["region", "product_category", "date"],
    compatibleCharts: ["line", "bar", "table"],
    summaryOperation: "sum",
    favorableDirection: "contextual",
  },
  {
    id: "operating_expense_ratio",
    name: "Operating Expense Ratio",
    category: "Efficiency",
    formula: "SUM(operating_expenses) / SUM(net_revenue) * 100",
    description:
      "Operating expenses as a percentage of revenue. Lower is more efficient.",
    unit: "%",
    cube: "OrdersCube",
    dimensions: ["region", "date"],
    compatibleCharts: ["line", "bar"],
    summaryOperation: "average",
    favorableDirection: "down",
  },
  {
    id: "customer_ltv",
    name: "Customer Lifetime Value",
    category: "Customer",
    formula: "ARPU * Average Customer Lifespan (months)",
    description:
      "Estimated total revenue a customer generates over their entire relationship.",
    unit: "USD",
    cube: "CustomersCube",
    dimensions: ["region", "customer_tier", "date"],
    compatibleCharts: ["bar", "table"],
    summaryOperation: "average",
    favorableDirection: "up",
  },
  {
    id: "mrr",
    name: "Monthly Recurring Revenue",
    category: "Revenue",
    formula: "SUM(active_subscription_mrr)",
    description:
      "Predictable monthly revenue generated by active subscription contracts.",
    unit: "USD",
    cube: "SubscriptionsCube",
    dimensions: ["region", "customer_tier", "date"],
    compatibleCharts: ["line", "bar", "table"],
    summaryOperation: "latest",
    favorableDirection: "up",
  },
  {
    id: "ebitda_margin",
    name: "EBITDA Margin",
    category: "Profitability",
    formula: "EBITDA / SUM(net_revenue) * 100",
    description:
      "Operating profitability before interest, taxes, depreciation, and amortization.",
    unit: "%",
    cube: "FinanceCube",
    dimensions: ["region", "product_category", "date"],
    compatibleCharts: ["line", "bar", "table"],
    summaryOperation: "average",
    favorableDirection: "up",
  },
  {
    id: "cac",
    name: "Customer Acquisition Cost",
    category: "Efficiency",
    formula: "SUM(sales_marketing_cost) / COUNT(new_customer_id)",
    description:
      "Average sales and marketing cost required to acquire one new customer.",
    unit: "USD",
    cube: "GrowthCube",
    dimensions: ["region", "customer_tier", "date"],
    compatibleCharts: ["line", "bar", "table"],
    summaryOperation: "average",
    favorableDirection: "down",
  },
  {
    id: "conversion_rate",
    name: "Conversion Rate",
    category: "Growth",
    formula: "COUNT(converted_sessions) / COUNT(eligible_sessions) * 100",
    description:
      "Percentage of eligible sessions that completed the target conversion.",
    unit: "%",
    cube: "GrowthCube",
    dimensions: ["region", "product_category", "date"],
    compatibleCharts: ["line", "bar", "table"],
    summaryOperation: "average",
    favorableDirection: "up",
  },
  {
    id: "refund_rate",
    name: "Refund Rate",
    category: "Efficiency",
    formula: "SUM(refunded_orders) / COUNT(order_id) * 100",
    description:
      "Percentage of completed orders that were later refunded.",
    unit: "%",
    cube: "OrdersCube",
    dimensions: ["region", "product_category", "date"],
    compatibleCharts: ["line", "bar", "table"],
    summaryOperation: "average",
    favorableDirection: "down",
  },
];

export function getMetricDefinition(id: string): MetricDefinition | undefined {
  return METRIC_CATALOG.find((metric) => metric.id === id);
}
